# Generated by Django 5.2.8 on 2025-11-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_zwierzecia', models.AutoField(db_column='ID_zwierzecia', primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('gatunek', models.CharField(max_length=50)),
                ('rasa', models.CharField(max_length=50)),
                ('wiek', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_oszacowania_wieku', models.DateField(blank=True, null=True)),
                ('data_przyjecia', models.DateField()),
                ('stan_zdrowia', models.TextField(blank=True)),
                ('kondycja_ciala', models.CharField(blank=True, max_length=50)),
                ('opis_charakteru', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('zdjecie', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'Zwierzeta',
            },
        ),
    ]
