# Generated by Django 5.2.8 on 2025-11-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_stan_zdrowia_alter_animal_wiek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('do_adopcji', 'Do adopcji'), ('w_trakcie', 'W trakcie adopcji'), ('adoptowany', 'Adoptowany')], default='do_adopcji', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='animals_photos/'),
        ),
    ]
