# Generated by Django 5.2.8 on 2026-01-10 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_medicalvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='medical_docs/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='animals.animal')),
            ],
            options={
                'ordering': ['-document_date', '-uploaded_at'],
            },
        ),
    ]
