# Generated by Django 5.2.8 on 2026-01-18 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Opis')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cel (PLN)')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Zebrano (PLN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Koniec zbiórki (opcjonalnie)')),
            ],
            options={
                'verbose_name': 'Zbiórka',
                'verbose_name_plural': 'Zbiórki',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kwota (PLN)')),
                ('donor_name', models.CharField(blank=True, max_length=120, verbose_name='Imie (opcjonalnie)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='fundraising.fundraiser')),
            ],
            options={
                'verbose_name': 'Wpłata',
                'verbose_name_plural': 'Wpłaty',
                'ordering': ['-created_at'],
            },
        ),
    ]
